import { money } from './agent.js';

const PAYMENT = {
  en: { ONLINE: 'payment link (KNET or card)', CASH: 'cash on delivery', CARD: 'card on delivery' },
  ar: { ONLINE: 'رابط دفع (كي نت أو بطاقة)', CASH: 'كاش عند الاستلام', CARD: 'بطاقة عند الاستلام' },
};

const dictionary = {
  en: {
    reviewOrder: ({ cart, customer: c, orderType, deliveryFee, paymentMethod, hasPin }) =>
      [
        'Please check your order:',
        cart,
        orderType === 'PICKUP' ? 'Pickup from the restaurant' : `Delivery fee: ${money(deliveryFee)}\nDeliver to: Area ${c.area}, Block ${c.block}, Street ${c.street}, Building ${c.building}${hasPin ? ' (map pin received)' : ''}`,
        `Payment: ${PAYMENT.en[paymentMethod] || paymentMethod}`,
        '',
        'Tap "Confirm order" or reply "yes" — or tell me what to change.',
      ].join('\n'),
    confirmButton: 'Confirm order',
    changeButton: 'Change something',
    confirmPrompt: 'Confirm this order?',
    whatToChange: 'Sure — what would you like to change?',
    unsupportedMessage: 'I can read text messages, voice notes and location pins. Please type or record what you would like.',
    unclearVoice: 'Sorry, I could not make out that voice note. Could you say it again, or type your order?',
    aiUnavailable: 'Our ordering assistant is offline for a moment — please try again shortly.',
    closed: (hours) => `We are closed right now. Working hours: ${hours}. You can still tell me what you would like and order once we open.`,
    minimumOrder: (min) => `The minimum order is ${money(min)} — shall I add something else?`,
    orderPlaced: (number, total) => `Order ${number} is confirmed. Total: ${money(total)}. The kitchen has it and I will keep you posted here.`,
    payNow: (number, total, link) => `Order ${number} is reserved — total ${money(total)}. Pay securely with KNET or card here:\n${link}\n\nThe kitchen starts as soon as the payment goes through.`,
    paymentReceived: (number) => `Payment received for order ${number} — thank you! The kitchen is starting on it now.`,
    paymentFailed: (number) => `The payment for order ${number} did not go through. You can try the link again, or reply "cash" to pay on delivery.`,
    paymentLinkUnavailable: 'The payment link is not available right now, so the order was placed as cash on delivery.',
    orderFailed: 'Something went wrong placing your order. Nothing was charged — please try again in a moment.',
    status: {
      CONFIRMED: (n) => `Order ${n} is confirmed by the kitchen.`,
      PREPARING: (n) => `Order ${n} is being prepared.`,
      READY: (n, type) => (type === 'PICKUP' ? `Order ${n} is ready for pickup!` : `Order ${n} is ready and on its way to you.`),
      DELIVERED: (n) => `Order ${n} has been delivered.`,
      CANCELLED: (n) => `Order ${n} was cancelled. Contact us if this was a mistake.`,
    },
    askReceipt: (n) => `Did you receive order ${n} in good condition?`,
    received: 'Yes, received',
    notReceived: 'Not yet',
    receiptThanks: 'Wonderful, enjoy your meal!',
    receiptProblem: 'Sorry about that. I have alerted the restaurant and someone will contact you right away.',
    askRating: 'How was everything? Rate your experience from 1 to 5.',
    invalidRating: 'Please reply with a number from 1 to 5.',
    askComments: 'Thank you! Any comments on the food, the delivery or our service? Reply "no" to skip.',
    feedbackThanks: 'Thank you for your feedback — it goes straight to the team. See you next time!',
    lastOrderStatus: (n, status) => `Your last order ${n} is currently: ${status.toLowerCase()}.`,
    noOrders: 'You have no orders with us yet.',
    cartCleared: 'Your cart is empty now. What would you like?',
    humanHandoff: 'I have passed this to the restaurant team; someone will get back to you here shortly.',
    kitchenProblem: (n, phone) => `Customer ${phone} reports order ${n} NOT received / a problem. Please contact them.`,
    kitchenHuman: (phone, text) => `Customer ${phone} asked for a person: "${text}"`,
    kitchenFeedback: (n, rating, comment) => `Feedback for order ${n}: ${rating}/5${comment ? ` — "${comment}"` : ''}`,
  },
  ar: {
    reviewOrder: ({ cart, customer: c, orderType, deliveryFee, paymentMethod, hasPin }) =>
      [
        'راجع طلبك لو سمحت:',
        cart,
        orderType === 'PICKUP' ? 'استلام من المطعم' : `رسوم التوصيل: ${money(deliveryFee)}\nالتوصيل إلى: منطقة ${c.area}، قطعة ${c.block}، شارع ${c.street}، مبنى ${c.building}${hasPin ? ' (وصلني الموقع على الخريطة)' : ''}`,
        `الدفع: ${PAYMENT.ar[paymentMethod] || paymentMethod}`,
        '',
        'اضغط "تأكيد الطلب" أو رد "إي"، أو قول لي شنو تبي تغيّر.',
      ].join('\n'),
    confirmButton: 'تأكيد الطلب',
    changeButton: 'أبي أغيّر شي',
    confirmPrompt: 'تأكد الطلب؟',
    whatToChange: 'أكيد، شنو تبي تغيّر؟',
    unsupportedMessage: 'أقدر أقرأ الرسائل المكتوبة والصوتية والموقع على الخريطة. اكتب أو سجّل طلبك لو سمحت.',
    unclearVoice: 'عذراً، ما قدرت أفهم الرسالة الصوتية. ممكن تعيدها أو تكتب طلبك؟',
    aiUnavailable: 'مساعد الطلبات غير متاح للحظات — جرّب مرة ثانية بعد قليل.',
    closed: (hours) => `المطعم مغلق حالياً. أوقات العمل: ${hours}. تقدر تقول لي طلبك وأجهزه لك أول ما نفتح.`,
    minimumOrder: (min) => `الحد الأدنى للطلب ${money(min)} — أضيف لك شي ثاني؟`,
    orderPlaced: (number, total) => `تم تأكيد الطلب ${number}. المجموع: ${money(total)}. المطبخ استلم الطلب وبخبرك هنا بكل جديد.`,
    payNow: (number, total, link) => `تم حفظ الطلب ${number} — المجموع ${money(total)}. ادفع بأمان بالكي نت أو البطاقة من هنا:\n${link}\n\nيبدأ المطبخ فور استلام الدفع.`,
    paymentReceived: (number) => `تم استلام الدفع للطلب ${number} — شكراً لك! المطبخ بدأ التجهيز.`,
    paymentFailed: (number) => `ما تم الدفع للطلب ${number}. تقدر تجرب الرابط مرة ثانية، أو رد "كاش" للدفع عند الاستلام.`,
    paymentLinkUnavailable: 'رابط الدفع غير متاح حالياً، فتم تسجيل الطلب دفع عند الاستلام.',
    orderFailed: 'صار خطأ أثناء تسجيل الطلب. ما تم خصم شي — جرّب مرة ثانية بعد قليل.',
    status: {
      CONFIRMED: (n) => `المطبخ أكد الطلب ${n}.`,
      PREPARING: (n) => `الطلب ${n} قيد التجهيز.`,
      READY: (n, type) => (type === 'PICKUP' ? `الطلب ${n} جاهز للاستلام!` : `الطلب ${n} جاهز وفي الطريق إليك.`),
      DELIVERED: (n) => `تم توصيل الطلب ${n}.`,
      CANCELLED: (n) => `تم إلغاء الطلب ${n}. تواصل معنا إذا كان هذا خطأ.`,
    },
    askReceipt: (n) => `هل استلمت الطلب ${n} بحالة جيدة؟`,
    received: 'نعم، استلمت',
    notReceived: 'ليس بعد',
    receiptThanks: 'ممتاز، بالعافية!',
    receiptProblem: 'نعتذر منك. بلّغت المطعم وبيتواصلون معك فوراً.',
    askRating: 'كيف كانت التجربة؟ قيّمنا من 1 إلى 5.',
    invalidRating: 'رد برقم من 1 إلى 5 لو سمحت.',
    askComments: 'شكراً! أي ملاحظات على الأكل أو التوصيل أو الخدمة؟ رد "لا" للتخطي.',
    feedbackThanks: 'شكراً على ملاحظاتك — توصل للفريق مباشرة. نشوفك المرة الجاية!',
    lastOrderStatus: (n, status) => `آخر طلب لك ${n} حالته الآن: ${status}.`,
    noOrders: 'ما عندك طلبات سابقة عندنا.',
    cartCleared: 'السلة فارغة الآن. شو تحب تطلب؟',
    humanHandoff: 'حوّلت الموضوع لفريق المطعم وبيردون عليك هنا قريباً.',
    kitchenProblem: (n, phone) => `العميل ${phone} يبلغ أن الطلب ${n} لم يُستلم / فيه مشكلة. الرجاء التواصل معه.`,
    kitchenHuman: (phone, text) => `العميل ${phone} يطلب التحدث مع شخص: "${text}"`,
    kitchenFeedback: (n, rating, comment) => `تقييم الطلب ${n}: ${rating}/5${comment ? ` — "${comment}"` : ''}`,
  },
};

export const t = (lang) => dictionary[lang === 'ar' ? 'ar' : 'en'];
