import { money } from './agent.js';

const PAYMENT = {
  en: { ONLINE: 'payment link (KNET or card)', CASH: 'cash on delivery', CARD: 'card on delivery' },
  ar: { ONLINE: 'رابط دفع (كي نت أو بطاقة)', CASH: 'كاش عند الاستلام', CARD: 'بطاقة عند الاستلام' },
};

const dictionary = {
  en: {
    reviewOrder: ({ cart, customer: c, orderType, deliveryFee, paymentMethod, hasPin }) =>
      [
        'Please check your order:',
        cart,
        orderType === 'PICKUP' ? 'Pickup from the restaurant' : `Delivery fee: ${money(deliveryFee)}\nDeliver to: Area ${c.area}, Block ${c.block}, Street ${c.street}, Building ${c.building}${hasPin ? ' (map pin received)' : ''}`,
        `Payment: ${PAYMENT.en[paymentMethod] || paymentMethod}`,
        '',
        'Tap "Confirm order" or reply "yes" — or tell me what to change.',
      ].join('\n'),
    confirmButton: 'Confirm order',
    changeButton: 'Change something',
    confirmPrompt: 'Confirm this order?',
    whatToChange: 'Sure — what would you like to change?',
    unsupportedMessage: 'I can read text messages, voice notes and location pins. Please type or record what you would like.',
    unclearVoice: 'Sorry, I could not make out that voice note. Could you say it again, or type your order?',
    aiUnavailable: 'Our ordering assistant is offline for a moment — please try again shortly.',
    closed: (hours) => `We are closed right now. Working hours: ${hours}. You can still tell me what you would like and order once we open.`,
    minimumOrder: (min) => `The minimum order is ${money(min)} — shall I add something else?`,
    orderPlaced: (number, total, items) =>
      `Order ${number} is confirmed.${items ? `\n${items}` : ''}\nTotal: ${money(total)}. The kitchen has it and I will keep you posted here.`,
    payNow: (number, total, link, items) =>
      `Order ${number} is reserved — total ${money(total)}.${items ? `\n${items}` : ''}\nPay securely with KNET or card here:\n${link}\n\nThe kitchen starts as soon as the payment goes through.`,
    welcome: 'Welcome to Mudawwarah! 👋 You can order by text or voice note. What would you like to do?',
    menuPrompt: 'How can I help you?',
    menuButton: 'Main menu',
    menuTitle: 'Mudawwarah',
    menuRows: [
      { id: 'menu:browse', title: 'Browse the menu', description: 'Categories, items and prices' },
      { id: 'menu:track', title: 'Track my order', description: 'Status of your latest order' },
      { id: 'menu:pay', title: 'Payment link', description: 'Pay your order by KNET or card' },
      { id: 'menu:complaint', title: 'Complaint / support', description: 'Report a problem to our team' },
      { id: 'menu:team', title: 'Talk to our team', description: 'Chat with a staff member' },
    ],
    browseIntro: 'Choose a category:',
    categoriesButton: 'Categories',
    itemsIntro: (category) => `${category} — tap an item to order it:`,
    itemsButton: 'Items',
    moreItems: 'More items…',
    wantItem: (name) => `I'd like ${name}`,
    onlinePaymentOff: 'Online payment is not available right now — you can pay cash or card on delivery.',
    noOrderToPay: 'You have no order waiting for payment yet. Tell me what you would like, and once the order is confirmed I will send the link for the exact amount.',
    kitchenPayOnline: (n) => `Order ${n}: customer switched to online payment — link sent.`,
    complaintAsk: 'Sorry to hear that. Please describe the problem (text or voice note) and I will pass it to our team.',
    complaintLogged: (ref) => `Your complaint is logged as ${ref}. Our team will review it and contact you shortly.`,
    kitchenComplaint: (ref, phone, order, text) => `Complaint ${ref} from ${phone}${order ? ` (order ${order})` : ''}: "${text}"`,
    paymentReceived: (number) => `Payment received for order ${number} — thank you! The kitchen is starting on it now.`,
    paymentFailed: (number) => `The payment for order ${number} did not go through. You can try the link again, or reply "cash" to pay on delivery.`,
    paymentLinkUnavailable: 'The payment link is not available right now, so the order was placed as cash on delivery.',
    orderFailed: 'Something went wrong placing your order. Nothing was charged — please try again in a moment.',
    status: {
      CONFIRMED: (n) => `Order ${n} is confirmed by the kitchen.`,
      PREPARING: (n) => `Order ${n} is being prepared.`,
      READY: (n, type) => (type === 'PICKUP' ? `Order ${n} is ready for pickup!` : `Order ${n} is ready and on its way to you.`),
      OUT_FOR_DELIVERY: (n) => `Order ${n} is out for delivery 🛵`,
      REACHED: (n) => `Our driver has reached your location with order ${n}.`,
      DELIVERED: (n) => `Order ${n} has been delivered.`,
      CANCELLED: (n) => `Order ${n} was cancelled. Contact us if this was a mistake.`,
    },
    statusLabel: {
      PENDING: 'received, waiting for the kitchen',
      CONFIRMED: 'confirmed',
      PREPARING: 'being prepared',
      READY: 'ready',
      OUT_FOR_DELIVERY: 'out for delivery',
      REACHED: 'driver has arrived',
      DELIVERED: 'delivered',
      CANCELLED: 'cancelled',
    },
    askReceipt: (n) => `Did you receive order ${n} in good condition?`,
    received: 'Yes, received',
    notReceived: 'Not yet',
    receiptThanks: 'Wonderful, enjoy your meal!',
    receiptProblem: 'Sorry about that. I have alerted the restaurant and someone will contact you right away.',
    askRating: 'How was everything? Rate your experience from 1 to 5.',
    invalidRating: 'Please reply with a number from 1 to 5.',
    askComments: 'Thank you! Any comments on the food, the delivery or our service? Reply "no" to skip.',
    feedbackThanks: 'Thank you for your feedback — it goes straight to the team. See you next time!',
    lastOrderStatus: (n, status) => `Your last order ${n} is currently: ${dictionary.en.statusLabel[status] || String(status).toLowerCase()}.`,
    noOrders: 'You have no orders with us yet.',
    cartCleared: 'Your cart is empty now. What would you like?',
    humanHandoff: 'I have passed this to the restaurant team; someone will get back to you here shortly.',
    kitchenProblem: (n, phone) => `Customer ${phone} reports order ${n} NOT received / a problem. Please contact them.`,
    kitchenHuman: (phone, text) => `Customer ${phone} asked for a person: "${text}"`,
    kitchenFeedback: (n, rating, comment) => `Feedback for order ${n}: ${rating}/5${comment ? ` — "${comment}"` : ''}`,
  },
  ar: {
    reviewOrder: ({ cart, customer: c, orderType, deliveryFee, paymentMethod, hasPin }) =>
      [
        'راجع طلبك لو سمحت:',
        cart,
        orderType === 'PICKUP' ? 'استلام من المطعم' : `رسوم التوصيل: ${money(deliveryFee)}\nالتوصيل إلى: منطقة ${c.area}، قطعة ${c.block}، شارع ${c.street}، مبنى ${c.building}${hasPin ? ' (وصلني الموقع على الخريطة)' : ''}`,
        `الدفع: ${PAYMENT.ar[paymentMethod] || paymentMethod}`,
        '',
        'اضغط "تأكيد الطلب" أو رد "إي"، أو قول لي شنو تبي تغيّر.',
      ].join('\n'),
    confirmButton: 'تأكيد الطلب',
    changeButton: 'أبي أغيّر شي',
    confirmPrompt: 'تأكد الطلب؟',
    whatToChange: 'أكيد، شنو تبي تغيّر؟',
    unsupportedMessage: 'أقدر أقرأ الرسائل المكتوبة والصوتية والموقع على الخريطة. اكتب أو سجّل طلبك لو سمحت.',
    unclearVoice: 'عذراً، ما قدرت أفهم الرسالة الصوتية. ممكن تعيدها أو تكتب طلبك؟',
    aiUnavailable: 'مساعد الطلبات غير متاح للحظات — جرّب مرة ثانية بعد قليل.',
    closed: (hours) => `المطعم مغلق حالياً. أوقات العمل: ${hours}. تقدر تقول لي طلبك وأجهزه لك أول ما نفتح.`,
    minimumOrder: (min) => `الحد الأدنى للطلب ${money(min)} — أضيف لك شي ثاني؟`,
    orderPlaced: (number, total, items) =>
      `تم تأكيد الطلب ${number}.${items ? `\n${items}` : ''}\nالمجموع: ${money(total)}. المطبخ استلم الطلب وبخبرك هنا بكل جديد.`,
    payNow: (number, total, link, items) =>
      `تم حفظ الطلب ${number} — المجموع ${money(total)}.${items ? `\n${items}` : ''}\nادفع بأمان بالكي نت أو البطاقة من هنا:\n${link}\n\nيبدأ المطبخ فور استلام الدفع.`,
    welcome: 'هلا والله ومرحبا فيك في مدورة! 👋 تقدر تطلب بالكتابة أو برسالة صوتية. شنو تحب تسوي؟',
    menuPrompt: 'شلون أقدر أخدمك؟',
    menuButton: 'القائمة',
    menuTitle: 'مدورة',
    menuRows: [
      { id: 'menu:browse', title: 'تصفح المنيو', description: 'الأقسام والأصناف والأسعار' },
      { id: 'menu:track', title: 'تتبع طلبي', description: 'حالة آخر طلب لك' },
      { id: 'menu:pay', title: 'رابط الدفع', description: 'ادفع طلبك بالكي نت أو البطاقة' },
      { id: 'menu:complaint', title: 'شكوى / مساعدة', description: 'بلّغ فريقنا عن أي مشكلة' },
      { id: 'menu:team', title: 'كلّم فريقنا', description: 'تواصل مع أحد الموظفين' },
    ],
    browseIntro: 'اختر القسم:',
    categoriesButton: 'الأقسام',
    itemsIntro: (category) => `${category} — اضغط على الصنف اللي تبيه:`,
    itemsButton: 'الأصناف',
    moreItems: 'أصناف أكثر…',
    wantItem: (name) => `أبي ${name}`,
    onlinePaymentOff: 'الدفع الإلكتروني غير متاح حالياً — تقدر تدفع كاش أو بطاقة عند الاستلام.',
    noOrderToPay: 'ما عندك طلب ينتظر الدفع للحين. قول لي شنو تبي، وأول ما نأكد الطلب برسل لك الرابط بالمبلغ بالضبط.',
    complaintAsk: 'نعتذر منك على هالشي. وصف لي المشكلة (كتابة أو صوت) وبوصلها لفريقنا.',
    complaintLogged: (ref) => `تم تسجيل شكواك برقم ${ref}. فريقنا بيراجعها ويتواصل معك قريب.`,
    paymentReceived: (number) => `تم استلام الدفع للطلب ${number} — شكراً لك! المطبخ بدأ التجهيز.`,
    paymentFailed: (number) => `ما تم الدفع للطلب ${number}. تقدر تجرب الرابط مرة ثانية، أو رد "كاش" للدفع عند الاستلام.`,
    paymentLinkUnavailable: 'رابط الدفع غير متاح حالياً، فتم تسجيل الطلب دفع عند الاستلام.',
    orderFailed: 'صار خطأ أثناء تسجيل الطلب. ما تم خصم شي — جرّب مرة ثانية بعد قليل.',
    status: {
      CONFIRMED: (n) => `المطبخ أكد الطلب ${n}.`,
      PREPARING: (n) => `الطلب ${n} قيد التجهيز.`,
      READY: (n, type) => (type === 'PICKUP' ? `الطلب ${n} جاهز للاستلام!` : `الطلب ${n} جاهز وفي الطريق إليك.`),
      OUT_FOR_DELIVERY: (n) => `طلبك ${n} طلع للتوصيل 🛵`,
      REACHED: (n) => `المندوب وصل عند موقعك بالطلب ${n}.`,
      DELIVERED: (n) => `تم توصيل الطلب ${n}.`,
      CANCELLED: (n) => `تم إلغاء الطلب ${n}. تواصل معنا إذا كان هذا خطأ.`,
    },
    statusLabel: {
      PENDING: 'مستلم وينتظر المطبخ',
      CONFIRMED: 'مؤكد',
      PREPARING: 'قيد التجهيز',
      READY: 'جاهز',
      OUT_FOR_DELIVERY: 'طالع للتوصيل',
      REACHED: 'المندوب وصل',
      DELIVERED: 'تم التوصيل',
      CANCELLED: 'ملغي',
    },
    askReceipt: (n) => `هل استلمت الطلب ${n} بحالة جيدة؟`,
    received: 'نعم، استلمت',
    notReceived: 'ليس بعد',
    receiptThanks: 'ممتاز، بالعافية!',
    receiptProblem: 'نعتذر منك. بلّغت المطعم وبيتواصلون معك فوراً.',
    askRating: 'كيف كانت التجربة؟ قيّمنا من 1 إلى 5.',
    invalidRating: 'رد برقم من 1 إلى 5 لو سمحت.',
    askComments: 'شكراً! أي ملاحظات على الأكل أو التوصيل أو الخدمة؟ رد "لا" للتخطي.',
    feedbackThanks: 'شكراً على ملاحظاتك — توصل للفريق مباشرة. نشوفك المرة الجاية!',
    lastOrderStatus: (n, status) => `آخر طلب لك ${n} حالته الآن: ${dictionary.ar.statusLabel[status] || status}.`,
    noOrders: 'ما عندك طلبات سابقة عندنا.',
    cartCleared: 'السلة فارغة الآن. شو تحب تطلب؟',
    humanHandoff: 'حوّلت الموضوع لفريق المطعم وبيردون عليك هنا قريباً.',
    kitchenProblem: (n, phone) => `العميل ${phone} يبلغ أن الطلب ${n} لم يُستلم / فيه مشكلة. الرجاء التواصل معه.`,
    kitchenHuman: (phone, text) => `العميل ${phone} يطلب التحدث مع شخص: "${text}"`,
    kitchenFeedback: (n, rating, comment) => `تقييم الطلب ${n}: ${rating}/5${comment ? ` — "${comment}"` : ''}`,
  },
};

export const t = (lang) => dictionary[lang === 'ar' ? 'ar' : 'en'];
